# This file can be used to customize the files managed by PDK.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
Gemfile:
  optional:
    ':development':
      - gem: 'puppet-resource_api'
        git: 'https://github.com/michaeltlombardi/puppet-resource_api'
        branch: 'gh-225/main/custom-insync'
      - gem: 'github_changelog_generator'
spec/spec_helper.rb:
  mock_with: ':rspec'
.gitlab-ci.yml:
  unmanaged: true
.travis.yml:
  unmanaged: true
appveyor.yml:
  unmanaged: true
data/common.yaml:
  unmanaged: true
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
